export default {
  WABA: {
    WABA: [
      'waba.waba.ALL',
      'waba.report.READ',
      'waba.template.READ',
      'waba.template.UPDATE',
      'waba.template.DELETE',
      'waba.template.CREATE',
      'waba.webhook.READ',
      'waba.webhook.CREATE',
      'waba.webhook.UPDATE',
      'waba.webhook.DELETE',
      'waba.profile.UPDATE',
      'waba.profile.READ',
    ],
  },
  CHANNEL_API: {
    CHANNEL: [
      'channel_api.channel.ALL',
      'channel_api.channel.READ',
      'channel_api.channel.UPDATE',
      'channel_api.channel.DELETE',
      'channel_api.channel.CREATE',
      'crm.channel.ALL',
      'crm.channel.READ',
      'crm.channel.UPDATE',
      'crm.channel.DELETE',
      'crm.channel.CREATE',
    ],
  },
  TASKS_BOT: {
    TASKS: ['tasksbot.task.ALL', 'tasksbot.task.READ', 'tasksbot.task.UPDATE', 'tasksbot.task.DELETE', 'tasksbot.task.CREATE'],
    WORKSPACE: [
      'tasksbot.workspace.ALL',
      'tasksbot.workspace.READ',
      'tasksbot.workspace.UPDATE',
      'tasksbot.workspace.DELETE',
      'tasksbot.workspace.CREATE',
    ],
  },
  PRODUCT66: {
    FOMO: ['fomo.panel.ALL'],
    MINISTE: ['minisite.panel.ALL'],
  },
  VIRTUAL_NUMBER: {
    NUMBER: [
      'virtual_number.number.ALL',
      'virtual_number.number.READ',
      'virtual_number.number.UPDATE',
      'virtual_number.number.CREATE',
      'virtual_number.number.DELETE',
    ],
    WEBHOOK: [
      'virtual_number.webhook.ALL',
      'virtual_number.webhook.READ',
      'virtual_number.webhook.UPDATE',
      'virtual_number.webhook.CREATE',
      'virtual_number.webhook.DELETE',
    ],
  },
  CRM: {
    CONTACT: ['crm.contact.ALL', 'crm.contact.READ', 'crm.contact.WRITE', 'crm.contact.DELETE', 'crm.contact.UPDATE'],
    CHANNEL: ['crm.channel.ALL', 'crm.channel.READ', 'crm.channel.WRITE', 'crm.channel.DELETE', 'crm.channel.UPDATE'],
    SEGMENT: ['crm.segment.ALL', 'crm.segment.READ', 'crm.segment.WRITE', 'crm.segment.DELETE', 'crm.segment.UPDATE'],
    CUSTOM_FIELD: [
      'crm.custom_field.ALL',
      'crm.custom_field.READ',
      'crm.custom_field.WRITE',
      'crm.custom_field.DELETE',
      'crm.custom_field.UPDATE',
    ],
    CANNED_REPLY: [
      'crm.canned_reply.ALL',
      'crm.canned_reply.READ',
      'crm.canned_reply.WRITE',
      'crm.canned_reply.DELETE',
      'crm.canned_reply.UPDATE',
    ],
    CAMPAIGN: ['crm.campaign.ALL', 'crm.campaign.READ', 'crm.campaign.WRITE', 'crm.campaign.DELETE', 'crm.campaign.UPDATE'],
    TRIGGER: ['crm.trigger.ALL', 'crm.trigger.READ', 'crm.trigger.WRITE', 'crm.trigger.DELETE', 'crm.trigger.UPDATE'],
    CHANNEL_GROUP: [
      'crm.channel_group.ALL',
      'crm.channel_group.READ',
      'crm.channel_group.WRITE',
      'crm.channel_group.DELETE',
      'crm.channel_group.UPDATE',
    ],
    MASS_BROADCAST: [
      'crm.mass_broadcast.ALL',
      'crm.mass_broadcast.READ',
      'crm.mass_broadcast.WRITE',
      'crm.mass_broadcast.DELETE',
      'crm.mass_broadcast.UPDATE',
    ],
    LIVE_CHAT: ['crm.live_chat.ALL', 'crm.live_chat.READ', 'crm.live_chat.WRITE', 'crm.live_chat.DELETE', 'crm.live_chat.UPDATE'],
  },
  BOT: {
    WORKFLOW: [
      'bot_builder.workflow.ALL',
      'bot_builder.workflow.READ',
      'bot_builder.workflow.WRITE',
      'bot_builder.workflow.DELETE',
      'bot_builder.workflow.UPDATE',
    ],
    DATA_STORE: [
      'bot_builder.data_store.ALL',
      'bot_builder.data_store.READ',
      'bot_builder.data_store.WRITE',
      'bot_builder.data_store.DELETE',
      'bot_builder.data_store.UPDATE',
    ],
    BOT_FIELD: [
      'bot_builder.bot_field.ALL',
      'bot_builder.bot_field.READ',
      'bot_builder.bot_field.WRITE',
      'bot_builder.bot_field.DELETE',
      'bot_builder.bot_field.UPDATE',
    ],
    TEMPLATE: [
      'bot_builder.template.ALL',
      'bot_builder.template.READ',
      'bot_builder.template.WRITE',
      'bot_builder.template.DELETE',
      'bot_builder.template.UPDATE',
    ],
    TEMPLATE_STORE: [
      'bot_builder.template_store.ALL',
      'bot_builder.template_store.READ',
      'bot_builder.template_store.WRITE',
      'bot_builder.template_store.DELETE',
      'bot_builder.template_store.UPDATE',
    ],
  },
  AUTOMATION: {
    WORKFLOW: [
      'automation.workflow.ALL',
      'automation.workflow.READ',
      'automation.workflow.WRITE',
      'automation.workflow.DELETE',
      'automation.workflow.UPDATE',
    ],
    DATA_STORE: [
      'automation.data_store.ALL',
      'automation.data_store.READ',
      'automation.data_store.WRITE',
      'automation.data_store.DELETE',
      'automation.data_store.UPDATE',
    ],
    TEMPLATE: [
      'automation.template.ALL',
      'automation.template.READ',
      'automation.template.WRITE',
      'automation.template.DELETE',
      'automation.template.UPDATE',
    ],
    TEMPLATE_STORE: [
      'automation.template_store.ALL',
      'automation.template_store.READ',
      'automation.template_store.WRITE',
      'automation.template_store.DELETE',
      'automation.template_store.UPDATE',
    ],
  },
  ECOMMERCE: {
    STORE: ['ecommerce.store.ALL', 'ecommerce.store.READ', 'ecommerce.store.UPDATE', 'ecommerce.store.CREATE', 'ecommerce.store.DELETE'],
    PRODUCT: [
      'ecommerce.product.ALL',
      'ecommerce.product.READ',
      'ecommerce.product.UPDATE',
      'ecommerce.product.CREATE',
      'ecommerce.product.DELETE',
    ],
    CART: ['ecommerce.cart.ALL', 'ecommerce.cart.READ', 'ecommerce.cart.UPDATE', 'ecommerce.cart.CREATE', 'ecommerce.cart.DELETE'],
    TRIGGER: [
      'ecommerce.trigger.ALL',
      'ecommerce.trigger.READ',
      'ecommerce.trigger.UPDATE',
      'ecommerce.trigger.CREATE',
      'ecommerce.trigger.DELETE',
    ],
    ORDER: ['ecommerce.order.ALL', 'ecommerce.order.READ', 'ecommerce.order.UPDATE', 'ecommerce.order.CREATE', 'ecommerce.order.DELETE'],
    ECOM_FIELD: [
      'ecommerce.ecom_field.ALL',
      'ecommerce.ecom_field.READ',
      'ecommerce.ecom_field.UPDATE',
      'ecommerce.ecom_field.CREATE',
      'ecommerce.ecom_field.DELETE',
    ],
    INQUIRY: [
      'ecommerce.inquiry.ALL',
      'ecommerce.inquiry.READ',
      'ecommerce.inquiry.UPDATE',
      'ecommerce.inquiry.CREATE',
      'ecommerce.inquiry.DELETE',
    ],
  },
  WAPPFLOW: {
    FLOWS: ['wappflow.flow.ALL', 'wappflow.flow.READ', 'wappflow.flow.WRITE', 'wappflow.flow.DELETE', 'wappflow.flow.UPDATE'],
  },
  CALENDAR: {
    CALENDAR: ['calendar.events.ALL', 'calendar.bookings.ALL'],
  },
  MEDIABOT: {
    MEDIABOT: ['mediabot.folder.ALL'],
  },
  REWARDZ: {
    REWARDZ: ['rewardz.panel.ALL'],
  },
  ANALYTICS: {
    CRM: ['analytics.crm.ALL'],
  },
  DIG: {
    IMAGE_EXPERIENCE: ['dig.img_exp.ALL', 'dig.img_exp.READ', 'dig.img_exp.CREATE', 'dig.img_exp.UPDATE', 'dig.img_exp.DELETE'],
    PDF_EXPERIENCE: ['dig.pdf_exp.ALL', 'dig.pdf_exp.READ', 'dig.pdf_exp.CREATE', 'dig.pdf_exp.UPDATE', 'dig.pdf_exp.DELETE'],
    storage: ['dig.pdf_exp.ALL', 'dig.pdf_exp.READ', 'dig.pdf_exp.CREATE', 'dig.pdf_exp.UPDATE', 'dig.pdf_exp.DELETE'],
  },
  LEAD_SOURCE: {
    LEAD_SOURCE: [
      'lead_source.sources.ALL',
      'lead_source.sources.READ',
      'lead_source.sources.CREATE',
      'lead_source.sources.UPDATE',
      'lead_source.sources.DELETE',
    ],
  },
  WIDGET: {
    WIDGET: [
      'chat_widget.widget.ALL',
      'chat_widget.widget.READ',
      'chat_widget.widget.CREATE',
      'chat_widget.widget.UPDATE',
      'chat_widget.widget.DELETE',
    ],
    LEADS: ['chat_widget.leads.ALL', 'chat_widget.leads.READ', 'chat_widget.leads.EXPORT'],
  },
  MINI_APP: {
    FLOW: [
      'mini_app.flow.ALL',
      'mini_app.flow.READ',
      'mini_app.flow.CREATE',
      'mini_app.flow.UPDATE',
      'mini_app.flow.SHARE',
      'mini_app.flow.PUBLISH',
      'mini_app.flow.LOCK',
      'mini_app.flow.DELETE',
    ],
    SUBMISSION: ['mini_app.submission.ALL', 'mini_app.submission.READ', 'mini_app.submission.EXPORT'],
    RUN_HISTORY: ['mini_app.history.ALL', 'mini_app.history.VIEW'],
  },

  CRM_V2: {
    CONTACT: ['crm_v2.contact.ALL', 'crm_v2.contact.READ', 'crm_v2.contact.WRITE', 'crm_v2.contact.DELETE', 'crm_v2.contact.UPDATE'],
    CHANNEL: ['crm_v2.channel.ALL', 'crm_v2.channel.READ', 'crm_v2.channel.WRITE', 'crm_v2.channel.DELETE', 'crm_v2.channel.UPDATE'],
    SEGMENT: ['crm_v2.segment.ALL', 'crm_v2.segment.READ', 'crm_v2.segment.WRITE', 'crm_v2.segment.DELETE', 'crm_v2.segment.UPDATE'],
    SUPER_FIELD: [
      'crm_v2.super_field.ALL',
      'crm_v2.super_field.READ',
      'crm_v2.super_field.WRITE',
      'crm_v2.super_field.DELETE',
      'crm_v2.super_field.UPDATE',
    ],
    CANNED_REPLY: [
      'crm_v2.canned_reply.ALL',
      'crm_v2.canned_reply.READ',
      'crm_v2.canned_reply.WRITE',
      'crm_v2.canned_reply.DELETE',
      'crm_v2.canned_reply.UPDATE',
    ],
    CAMPAIGN: ['crm_v2.campaign.ALL', 'crm_v2.campaign.READ', 'crm_v2.campaign.WRITE', 'crm_v2.campaign.DELETE', 'crm_v2.campaign.UPDATE'],
    TRIGGER: ['crm_v2.trigger.ALL', 'crm_v2.trigger.READ', 'crm_v2.trigger.WRITE', 'crm_v2.trigger.DELETE', 'crm_v2.trigger.UPDATE'],
    SHEET: ['crm_v2.sheet.ALL', 'crm_v2.sheet.READ', 'crm_v2.sheet.WRITE', 'crm_v2.sheet.DELETE', 'crm_v2.sheet.UPDATE'],
    BOARD: ['crm_v2.board.ALL', 'crm_v2.board.READ', 'crm_v2.board.WRITE', 'crm_v2.board.DELETE', 'crm_v2.board.UPDATE'],
    LIVE_CHAT: [
      'crm_v2.live_chat.ALL',
      'crm_v2.live_chat.READ',
      'crm_v2.live_chat.WRITE',
      'crm_v2.live_chat.DELETE',
      'crm_v2.live_chat.UPDATE',
    ],
    DATA_STORE: [
      'crm_v2.data_store.ALL',
      'crm_v2.data_store.READ',
      'crm_v2.data_store.WRITE',
      'crm_v2.data_store.DELETE',
      'crm_v2.data_store.UPDATE',
    ],
    IMPORT: ['crm_v2.import.ALL', 'crm_v2.import.READ'],
    EXPORT: ['crm_v2.export.ALL', 'crm_v2.export.READ'],
  },

  NATIVE_PAYMENT: {
    PURCHASE_ORDER: ['payment.po.ALL', 'payment.po.READ', 'payment.po.CREATE', 'payment.po.UPDATE', 'payment.po.DELETE'],
    PAYMENT_GATEWAY: ['payment.pg.ALL', 'payment.pg.READ', 'payment.pg.CREATE', 'payment.pg.UPDATE', 'payment.pg.DELETE'],
    WEBHOOK: ['payment.webhook.ALL', 'payment.webhook.READ', 'payment.webhook.CREATE', 'payment.webhook.UPDATE', 'payment.webhook.DELETE'],
  },

  DEPARTMENT: {
    DEPARTMENT: [
      'department.department.ALL',
      'department.department.READ',
      'department.department.CREATE',
      'department.department.UPDATE',
      'department.department.DELETE',
    ],
    AGENTS: [
      'department.agent.ALL',
      'department.agent.READ',
      'department.agent.CREATE',
      'department.agent.UPDATE',
      'department.agent.DELETE',
    ],
    ANALYTICS: [
      'department.analytics.ALL',
      'department.analytics.READ',
      'department.analytics.CREATE',
      'department.analytics.UPDATE',
      'department.analytics.DELETE',
    ],
    ROLE: ['department.role.ALL', 'department.role.READ', 'department.role.UPDATE'],
  },
};
