// Actions
export const API_RESPONSE_SUCCESS = 'API_RESPONSE_SUCCESS';
export const API_RESPONSE_ERROR = 'API_RESPONSE_ERROR';

export const GET_USER_RNP = 'GET_USER_RNP';
export const GET_USER_STOKEN = 'GET_USER_STOKEN';
export const GET_USER_WALLET_BALANCE = 'GET_USER_WALLET_BALANCE';

export const RESET_USER_RNP = 'RESET_USER_RNP';
