const DefaultMenu = {
  DEFAULT: [
    {
      type: 'header',
      id: 'header_menu',
      label: 'Menu',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'dashboard',
      label: 'All Products',
      icon: 'bx bxs-dashboard',
      link: '/products',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'workspace',
      label: 'Workspace',
      icon: 'bx bxs-network-chart',
      link: '/workspace',
      permission: 'EMPTY',
    },
    {
      type: 'header',
      id: 'header_crm_v2',
      label: 'WhatsApp Business API',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'dashboard',
      label: 'WABA',
      icon: 'bx bxl-whatsapp',
      link: '/products/waba',
      permission: 'WABA.WABA',
    },
    {
      type: 'header',
      id: 'header_crm_v2',
      label: 'Channels',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'channel',
      label: 'Channel',
      icon: 'bx bx-git-compare',
      link: '/products/channel',
      permission: 'CHANNEL_API.CHANNEL',
    },
    {
      type: 'header',
      id: 'header_crm_v2',
      label: 'CRM V1',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'livechat',
      label: 'Live Chat',
      icon: 'bx bxs-chat',
      link: '/products/crm/livechat',
      permission: 'CRM.LIVE_CHAT',
    },
    {
      type: 'page',
      id: 'channel',
      label: 'Channels',
      icon: 'bx bx-git-compare',
      link: '/products/crm/channel',
      permission: 'CRM.CHANNEL',
    },
    {
      type: 'page',
      id: 'contact',
      label: 'Contacts',
      icon: 'bx bxs-contact',
      link: '/products/crm/contact',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'custom-field',
      label: 'Custom Fields',
      icon: 'bx bxs-tag-alt',
      link: '/products/crm/custom-field',
      permission: 'CRM.CUSTOM_FIELD',
    },
    {
      type: 'page',
      id: 'canned-replies',
      label: 'Canned Replies',
      icon: 'bx bxs-message-detail',
      link: '/products/crm/canned-replies',
      permission: 'CRM.CANNED_REPLY',
    },
    {
      type: 'page',
      id: 'filter-list',
      label: 'Segments',
      icon: 'bx bx-filter',
      link: '/products/crm/filter-list',
      permission: 'CRM.SEGMENT',
    },
    {
      type: 'page',
      id: 'campaign',
      label: 'Campaign',
      icon: 'bx bxs-megaphone',
      link: '/products/crm/campaign',
      new: true,
      tag: 'New',
      tagClass: 'badge bg-primary',
      permission: 'CRM.CAMPAIGN',
    },
    {
      type: 'page',
      id: 'channel-group',
      label: 'Channel Group',
      icon: 'bx bx-merge',
      link: '/products/crm/channel-group',
      permission: 'CRM.CHANNEL_GROUP',
    },
    {
      type: 'page',
      id: 'mass-broadcast',
      label: 'Mass Broadcast',
      icon: 'bx bx-broadcast',
      link: '/products/crm/mass-broadcast',
      permission: 'CRM.MASS_BROADCAST',
    },
    {
      type: 'page',
      id: 'automation_trigger',
      label: 'Triggers',
      icon: 'bx bx-link',
      link: '/products/crm/automation/trigger',
      permission: 'CRM.TRIGGER',
    },
    {
      type: 'header',
      id: 'header_crm_v2',
      label: 'CRM V2',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'live_chat',
      label: 'Live Chat',
      icon: 'bx bx-conversation',
      link: '/products/crmv2/chat/0',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'contact_v2',
      label: 'Contacts',
      icon: 'bx bxs-book',
      link: '/products/crmv2/contacts',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'channel',
      label: 'Channels',
      icon: 'bx bx-git-compare',
      link: '/products/crmv2/channelv2',
      permission: 'CRM.CHANNEL',
    },
    {
      type: 'page',
      id: 'campaigns',
      label: 'Campaign',
      icon: 'bx bxs-megaphone',
      link: '/products/crmv2/campaign',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'boards',
      label: 'Boards',
      icon: 'bx bx-chalkboard',
      link: '/products/crmv2/boards',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'sheets',
      label: 'Sheets',
      icon: 'bx bx-spreadsheet',
      link: '/products/crmv2/sheets',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'dataStores',
      label: 'Data Stores',
      icon: 'bx bxs-data',
      link: '/products/crmv2/data-store',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'segments',
      label: 'Segments',
      icon: 'bx bx-filter-alt',
      link: '/products/crmv2/segments',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'canned_replies',
      label: 'Canned Replies',
      icon: 'bx bxs-bolt',
      link: '/products/crmv2/quick-reply',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'super_field',
      label: 'Super Field',
      icon: 'bx bx-customize',
      link: '/products/crmv2/super-field',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'import_history',
      label: 'Import History',
      icon: 'bx bx-import',
      link: '/products/crmv2/import',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'export_history',
      label: 'Export History',
      icon: 'bx bx-export',
      link: '/products/crmv2/export',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'crm_trigger',
      label: 'CRM Trigger',
      icon: 'bx bx-link',
      link: '/products/crmv2/trigger',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'header',
      id: 'header_setting',
      label: 'Automation Builder',
      permission: 'CRM.CHANNEL',
    },
    {
      type: 'page',
      id: 'automation_analytics',
      label: 'Analytics',
      icon: 'ri-line-chart-line',
      link: '/products/automation/analytics',
      permission: 'AUTOMATION.WORKFLOW',
    },
    {
      type: 'page',
      id: 'automation_flow',
      label: 'Workflow',
      icon: 'ri-stackshare-line',
      link: '/products/automation/flow',
      permission: 'AUTOMATION.WORKFLOW',
    },
    {
      type: 'page',
      id: 'my_automation_template',
      label: 'My Templates',
      icon: 'bx bxs-book-content',
      link: '/products/automation/my-template',
      permission: 'AUTOMATION.TEMPLATE',
    },
    {
      type: 'page',
      id: 'automation_template_stote',
      label: 'Template Store',
      icon: 'bx bxs-book-bookmark',
      link: '/products/automation/template',
      permission: 'AUTOMATION.TEMPLATE_STORE',
    },
    {
      type: 'header',
      id: 'header_setting',
      label: 'Bot Builder',
      permission: 'CRM.CHANNEL',
    },
    {
      type: 'page',
      id: 'analytics',
      label: 'Analytics',
      icon: 'ri-line-chart-line',
      link: '/products/bot/analytics',
      permission: 'BOT.WORKFLOW',
    },
    {
      type: 'page',
      id: 'flow',
      label: 'Workflow',
      icon: 'ri-stackshare-line',
      link: '/products/bot/flow',
      permission: 'BOT.WORKFLOW',
    },
    {
      type: 'page',
      id: 'my-template',
      label: 'My Templates',
      icon: 'bx bxs-book-content',
      link: '/products/bot/my-template',
      permission: 'BOT.TEMPLATE',
    },
    {
      type: 'page',
      id: 'my-template',
      label: 'Template Store',
      icon: 'bx bxs-book-bookmark',
      link: '/products/bot/template',
      permission: 'BOT.TEMPLATE_STORE',
    },
    {
      type: 'page',
      id: 'data-store',
      label: 'Data Store',
      icon: 'bx bxs-data',
      link: '/products/bot/data-store',
      permission: 'BOT.DATA_STORE',
    },
    {
      type: 'page',
      id: 'bot-content',
      label: 'Bot Fields',
      icon: 'bx bx-code-alt',
      link: '/products/bot/bot-field',
      permission: 'BOT.BOT_FIELD',
    },
    {
      type: 'header',
      id: 'header_setting',
      label: 'Virtual Number',
      permission: 'CRM.CHANNEL',
    },
    {
      type: 'page',
      id: 'virtual_number',
      label: 'Virtual Numbers',
      icon: 'bx bxs-phone-call',
      link: '/products/virtual_number',
      permission: 'VIRTUAL_NUMBER.NUMBER',
    },
    {
      type: 'header',
      id: 'header_setting',
      label: 'WhatsApp Mini-Apps',
      permission: 'CRM.CHANNEL',
    },
    {
      type: 'page',
      id: 'flow',
      label: 'Flows',
      new: true,
      tag: 'Beta',
      tagClass: 'badge bg-info',
      icon: 'bx bx-fullscreen',
      link: '/products/flows',
      permission: 'CRM.CHANNEL',
    },
    {
      type: 'header',
      id: 'header_setting',
      label: 'WhatsApp Widget',
      permission: 'CRM.CHANNEL',
    },
    {
      type: 'page',
      id: 'widget',
      label: 'Widget',
      new: true,
      tag: 'Beta',
      tagClass: 'badge bg-info',
      icon: 'bx bx-conversation',
      link: '/products/widget',
      permission: 'CRM.CHANNEL',
    },
    {
      type: 'header',
      id: 'header_setting',
      label: 'WhatsApp Native Payments',
      permission: 'CRM.CHANNEL',
    },
    {
      type: 'page',
      id: 'payment_orders',
      label: 'Payment Orders',
      icon: 'bx bx-file',
      link: '/products/payment/order',
      permission: 'CRM.CHANNEL',
    },
    {
      type: 'header',
      id: 'header_setting',
      label: 'Settings',
      permission: 'CRM.CHANNEL',
    },
    {
      type: 'page',
      id: 'payment_gateway',
      label: 'Payment Gateways',
      icon: 'bx bxs-bank',
      link: '/products/payment/gateway',
      permission: 'CRM.CHANNEL',
    },
    {
      type: 'page',
      id: 'payment_automation',
      label: 'Automations',
      icon: 'bx bx-cog',
      link: '/products/payment/automation',
      permission: 'CRM.CHANNEL',
    },
    {
      type: 'header',
      id: 'header_dig',
      label: 'Dynamic Experiences',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'image_experience',
      label: 'Image Experience',
      icon: 'bx bx-image',
      link: '/image',
      permission: 'CRM.CHANNEL',
    },

    //check pdf
    // {
    //   type: 'page',
    //   id: 'pdf_experience',
    //   label: 'PDF Experience',
    //   icon: 'bx bx-image',
    //   link: '/pdf',
    //   permission: 'CRM.CHANNEL',
    // },
    {
      type: 'header',
      id: 'header_manage_team',
      label: 'Manage Team',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'roleandpermission',
      label: 'Roles & Permissions',
      icon: 'bx bxs-user-badge',
      link: '/workspace/user-role',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'team-member',
      label: 'Team Members',
      icon: 'bx bxs-user-account',
      link: '/workspace/team-member',
      permission: 'EMPTY',
    },
    {
      type: 'header',
      id: 'header_settings',
      label: 'Settings',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'profile-settings',
      label: 'Account Settings',
      icon: 'bx bxs-cog',
      link: '/workspace/settings',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'wallet',
      label: 'Wallet & Transactions',
      icon: 'bx bxs-wallet',
      link: '/workspace/wallet',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'billing',
      label: 'Billing',
      icon: 'bx bxs-credit-card',
      link: '/workspace/billing',
      permission: 'EMPTY',
    },
    {
      type: 'header',
      id: 'affilite_settings',
      label: 'Affiliate',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'affiliate-visitor',
      label: 'Visitors & Conversion',
      icon: 'ri-eye-fill',
      link: '/workspace/affiliate/vnc',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'affiliate-payout',
      label: 'Commission & Payout',
      icon: 'ri-bank-fill',
      link: '/workspace/affiliate/cnp',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'affiliate-link',
      label: 'Links & Alias',
      icon: 'bx bx-link',
      link: '/workspace/affiliate/settings',
      permission: 'EMPTY',
    },
    {
      type: 'header',
      id: 'header_help',
      label: 'Help & Support',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'support-ticket',
      label: 'Support Ticket',
      icon: 'las la-life-ring',
      link: '/workspace/ticket',
      permission: 'EMPTY',
    },
  ],
  PROFILE: [
    {
      id: '1',
      label: 'Balance: {{wallet_balance}} {{wallet_currency}}',
      icon: 'bx bxs-wallet-alt',
      link: '#',
      type: 'page',
    },
    {
      id: '2',
      type: 'divider',
    },
    {
      id: '3',
      type: 'header',
      label: 'Settings',
    },
    {
      id: '4',
      label: 'Profile',
      icon: 'mdi mdi-account-circle',
      link: '/workspace/settings',
      type: 'page',
    },
    {
      id: '5',
      label: 'Wallet & Transactions',
      icon: 'bx bxs-wallet',
      link: '/workspace/wallet',
      type: 'page',
    },
    {
      id: '6',
      type: 'page',
      label: 'Billing',
      icon: 'bx bxs-credit-card',
      link: '/workspace/billing',
    },
    {
      id: '7',
      type: 'divider',
    },
    {
      id: '8',
      type: 'header',
      label: 'Support',
    },
    {
      id: '9',
      type: 'page',
      label: 'Support Ticket',
      icon: 'mdi mdi-lifebuoy',
      link: '/workspace/ticket',
    },
  ],
  HOME: [
    {
      type: 'header',
      id: 'header_menu',
      label: 'Menu',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'dashboard',
      label: 'All Products',
      icon: 'bx bxs-dashboard',
      link: '/products',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'workspace',
      label: 'Workspace',
      icon: 'bx bxs-network-chart',
      link: '/workspace',
      permission: 'EMPTY',
    },
  ],
  WABA: [
    {
      type: 'header',
      id: 'header_menu',
      label: 'Menu',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'dashboard',
      label: 'All Products',
      icon: 'bx bxs-dashboard',
      link: '/products',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'dashboard',
      label: 'WABA',
      icon: 'bx bxl-whatsapp',
      link: '/products/waba',
      permission: 'WABA.WABA',
    },
  ],
  CHANNEL: [
    {
      type: 'header',
      id: 'header_menu',
      label: 'Menu',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'dashboard',
      label: 'All Products',
      icon: 'bx bxs-dashboard',
      link: '/products',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'channel',
      label: 'Channel',
      icon: 'bx bx-git-compare',
      link: '/products/channel',
      permission: 'CHANNEL_API.CHANNEL',
    },
  ],
  CRM: [
    {
      type: 'header',
      id: 'header_crm',
      label: 'Menu',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'dashboard',
      label: 'All Products',
      icon: 'bx bxs-dashboard',
      link: '/products',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'livechat',
      label: 'Live Chat',
      icon: 'bx bxs-chat',
      link: '/products/crm/livechat',
      permission: 'CRM.LIVE_CHAT',
    },
    {
      type: 'page',
      id: 'channel',
      label: 'Channels',
      icon: 'bx bx-git-compare',
      link: '/products/crm/channel',
      permission: 'CRM.CHANNEL',
    },
    {
      type: 'page',
      id: 'contact',
      label: 'Contacts',
      icon: 'bx bxs-contact',
      link: '/products/crm/contact',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'custom-field',
      label: 'Custom Fields',
      icon: 'bx bxs-tag-alt',
      link: '/products/crm/custom-field',
      permission: 'CRM.CUSTOM_FIELD',
    },
    {
      type: 'page',
      id: 'canned-replies',
      label: 'Canned Replies',
      icon: 'bx bxs-message-detail',
      link: '/products/crm/canned-replies',
      permission: 'CRM.CANNED_REPLY',
    },
    {
      type: 'header',
      id: 'header_broadcasting',
      label: 'Broadcasting',
      permission: 'CRM.CAMPAIGN',
    },
    {
      type: 'page',
      id: 'filter-list',
      label: 'Segments',
      icon: 'bx bx-filter',
      link: '/products/crm/filter-list',
      permission: 'CRM.SEGMENT',
    },
    {
      type: 'page',
      id: 'campaign',
      label: 'Campaign',
      icon: 'bx bxs-megaphone',
      link: '/products/crm/campaign',
      new: true,
      tag: 'New',
      tagClass: 'badge bg-primary',
      permission: 'CRM.CAMPAIGN',
    },
    {
      type: 'header',
      id: 'header_mass_broadcasting',
      label: 'Mass Broadcasting',
      permission: 'CRM.CHANNEL_GROUP',
    },
    {
      type: 'page',
      id: 'channel-group',
      label: 'Channel Group',
      icon: 'bx bx-merge',
      link: '/products/crm/channel-group',
      permission: 'CRM.CHANNEL_GROUP',
    },
    {
      type: 'page',
      id: 'mass-broadcast',
      label: 'Mass Broadcast',
      icon: 'bx bx-broadcast',
      link: '/products/crm/mass-broadcast',
      permission: 'CRM.MASS_BROADCAST',
    },
    {
      type: 'header',
      id: 'header_automations',
      label: 'Automations',
      permission: 'CRM.TRIGGER',
    },
    {
      type: 'page',
      id: 'automation_trigger',
      label: 'Triggers',
      icon: 'bx bx-link',
      link: '/products/crm/automation/trigger',
      permission: 'CRM.TRIGGER',
    },
  ],
  CRMV2: [
    {
      type: 'header',
      id: 'header_crm',
      label: 'Menu',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'dashboard',
      label: 'All Products',
      icon: 'bx bxs-dashboard',
      link: '/products',
      permission: 'EMPTY',
    },
    {
      type: 'header',
      id: 'header_crm_v2',
      label: 'Module',
      permission: 'CRM_V2.CONTACT',
    },
    {
      type: 'page',
      id: 'live_chat',
      label: 'Live Chat',
      icon: 'bx bx-conversation',
      link: '/products/crmv2/chat/0',
      permission: 'CRM_V2.CONTACT',
    },
    {
      type: 'page',
      id: 'contact_v2',
      label: 'Contacts',
      icon: 'bx bxs-book',
      link: '/products/crmv2/contacts',
      permission: 'CRM_V2.CONTACT',
    },
    {
      type: 'page',
      id: 'channel',
      label: 'Channels',
      icon: 'bx bx-git-compare',
      link: '/products/crmv2/channelv2',
      permission: 'CRM_V2.CHANNEL',
    },
    {
      type: 'page',
      id: 'campaigns',
      label: 'Campaign',
      icon: 'bx bxs-megaphone',
      link: '/products/crmv2/campaign',
      permission: 'CRM_V2.CAMPAIGN',
    },
    {
      type: 'header',
      id: 'header_crm_v2_views',
      label: 'Views',
      permission: 'CRM_V2.BOARD',
    },
    {
      type: 'page',
      id: 'boards',
      label: 'Boards',
      icon: 'bx bx-chalkboard',
      link: '/products/crmv2/boards',
      permission: 'CRM_V2.BOARD',
    },
    {
      type: 'page',
      id: 'sheets',
      label: 'Sheets',
      icon: 'bx bx-spreadsheet',
      link: '/products/crmv2/sheets',
      permission: 'CRM_V2.SHEET',
    },
    {
      type: 'page',
      id: 'dataStores',
      label: 'Data Stores',
      icon: 'bx bxs-data',
      link: '/products/crmv2/data-store',
      permission: 'CRM_V2.DATA_STORE',
    },
    {
      type: 'header',
      id: 'header_crm_v2_utility',
      label: 'Utility',
      permission: 'CRM_V2.SEGMENT',
    },
    {
      type: 'page',
      id: 'segments',
      label: 'Segments',
      icon: 'bx bx-filter-alt',
      link: '/products/crmv2/segments',
      permission: 'CRM_V2.SEGMENT',
    },
    {
      type: 'page',
      id: 'canned_replies',
      label: 'Canned Replies',
      icon: 'bx bxs-bolt',
      link: '/products/crmv2/quick-reply',
      permission: 'CRM_V2.CANNED_REPLY',
    },
    {
      type: 'page',
      id: 'super_field',
      label: 'Super Field',
      icon: 'bx bx-customize',
      link: '/products/crmv2/super-field',
      permission: 'CRM_V2.SUPER_FIELD',
    },
    {
      type: 'page',
      id: 'import_history',
      label: 'Import History',
      icon: 'bx bx-import',
      link: '/products/crmv2/import',
      permission: 'CRM_V2.IMPORT',
    },
    {
      type: 'page',
      id: 'export_history',
      label: 'Export History',
      icon: 'bx bx-export',
      link: '/products/crmv2/export',
      permission: 'CRM_V2.EXPORT',
    },
    {
      type: 'header',
      id: 'header_crm_v2_settings',
      label: 'Settings',
      permission: 'CRM_V2.TRIGGER',
    },
    {
      type: 'page',
      id: 'crm_trigger',
      label: 'CRM Trigger',
      icon: 'bx bx-link',
      link: '/products/crmv2/trigger',
      permission: 'CRM_V2.TRIGGER',
    },
  ],
  TASKSBOT: [
    {
      type: 'header',
      id: 'header_crm',
      label: 'Menu',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'dashboard',
      label: 'All Products',
      icon: 'bx bxs-dashboard',
      link: '/products',
      permission: 'EMPTY',
    },
    {
      type: 'header',
      id: 'header_tasks',
      label: 'Tasks',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'tasks_manager',
      label: 'Tasks',
      icon: 'bx bx-task',
      link: '/products/tasks',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'header',
      id: 'task_workspace_header',
      label: 'Workspace',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'tasks_workspace',
      label: 'Workspaces',
      icon: 'bx bx-network-chart',
      link: '/products/tasks/hub',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'header',
      id: 'tasks_settings_header',
      label: 'Settings',
      permission: 'CRM.CONTACT',
    },
    {
      type: 'page',
      id: 'task_profile',
      label: 'Profile',
      icon: 'bx bx-user-circle',
      link: '/products/tasks/settings',
      permission: 'CRM.CONTACT',
    },
  ],
  AUTOMATION: [
    {
      type: 'header',
      id: 'header_automation',
      label: 'Menu',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'dashboard_automation',
      label: 'All Products',
      icon: 'bx bxs-dashboard',
      link: '/products',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'automation_analytics',
      label: 'Analytics',
      icon: 'ri-line-chart-line',
      link: '/products/automation/analytics',
      permission: 'AUTOMATION.WORKFLOW',
    },
    {
      type: 'page',
      id: 'automation_flow',
      label: 'Workflow',
      icon: 'ri-stackshare-line',
      link: '/products/automation/flow',
      permission: 'AUTOMATION.WORKFLOW',
    },
    {
      type: 'header',
      id: 'header_template',
      label: 'Template',
      permission: 'AUTOMATION.TEMPLATE',
    },
    {
      type: 'page',
      id: 'my_automation_template',
      label: 'My Templates',
      icon: 'bx bxs-book-content',
      link: '/products/automation/my-template',
      permission: 'AUTOMATION.TEMPLATE',
    },
    {
      type: 'page',
      id: 'automation_template_stote',
      label: 'Template Store',
      icon: 'bx bxs-book-bookmark',
      link: '/products/automation/template',
      permission: 'AUTOMATION.TEMPLATE_STORE',
    },
    {
      type: 'header',
      id: 'header_integration',
      label: 'Integration',
      permission: 'AUTOMATION.DATA_STORE',
    },
    {
      type: 'page',
      id: 'data_store',
      label: 'Data Store',
      icon: 'bx bxs-data',
      link: '/products/automation/data-store',
      permission: 'AUTOMATION.DATA_STORE',
    },
  ],
  BOT_BUILDER: [
    {
      type: 'header',
      id: 'header_automation',
      label: 'Menu',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'dashboard_automation',
      label: 'All Products',
      icon: 'bx bxs-dashboard',
      link: '/products',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'analytics',
      label: 'Analytics',
      icon: 'ri-line-chart-line',
      link: '/products/bot/analytics',
      permission: 'BOT.WORKFLOW',
    },
    {
      type: 'page',
      id: 'flow',
      label: 'Workflow',
      icon: 'ri-stackshare-line',
      link: '/products/bot/flow',
      permission: 'BOT.WORKFLOW',
    },
    {
      type: 'header',
      id: 'header_template',
      label: 'Template',
      permission: 'BOT.TEMPLATE',
    },
    {
      type: 'page',
      id: 'my-template',
      label: 'My Templates',
      icon: 'bx bxs-book-content',
      link: '/products/bot/my-template',
      permission: 'BOT.TEMPLATE',
    },
    {
      type: 'page',
      id: 'my-template',
      label: 'Template Store',
      icon: 'bx bxs-book-bookmark',
      link: '/products/bot/template',
      permission: 'BOT.TEMPLATE_STORE',
    },
    {
      type: 'header',
      label: 'Integration',
      permission: 'BOT.DATA_STORE',
    },
    {
      type: 'page',
      id: 'data-store',
      label: 'Data Store',
      icon: 'bx bxs-data',
      link: '/products/bot/data-store',
      permission: 'BOT.DATA_STORE',
    },
    {
      type: 'header',
      label: 'Content',
      permission: 'BOT.BOT_FIELD',
    },
    {
      type: 'page',
      id: 'bot-content',
      label: 'Bot Fields',
      icon: 'bx bx-code-alt',
      link: '/products/bot/bot-field',
      permission: 'BOT.BOT_FIELD',
    },
  ],
  VIRTUAL_NUMBER: [
    {
      type: 'header',
      id: 'header_automation',
      label: 'Menu',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'dashboard_automation',
      label: 'All Products',
      icon: 'bx bxs-dashboard',
      link: '/products',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'virtual_number',
      label: 'Virtual Numbers',
      icon: 'bx bxs-phone-call',
      link: '/products/virtual_number',
      permission: 'VIRTUAL_NUMBER.NUMBER',
    },
    // {
    //   type: 'page',
    //   id: 'virtual_webhook',
    //   label: 'Webhooks',
    //   icon: 'bx bx-link',
    //   link: '/products/virtual_number/webhook',
    //   permission: 'VIRTUAL_NUMBER.NUMBER',
    // },
  ],
  WORKSPACE: [
    {
      type: 'header',
      id: 'header_automation',
      label: 'Menu',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'dashboard_automation',
      label: 'All Products',
      icon: 'bx bxs-dashboard',
      link: '/products',
      permission: 'EMPTY',
    },
    {
      type: 'header',
      id: 'header_manage_team',
      label: 'Manage Team',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'roleandpermission',
      label: 'Roles & Permissions',
      icon: 'bx bxs-user-badge',
      link: '/workspace/user-role',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'team-member',
      label: 'Team Members',
      icon: 'bx bxs-user-account',
      link: '/workspace/team-member',
      permission: 'EMPTY',
    },
    {
      type: 'header',
      id: 'header_settings',
      label: 'Settings',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'profile-settings',
      label: 'Account Settings',
      icon: 'bx bxs-cog',
      link: '/workspace/settings',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'wallet',
      label: 'Wallet & Transactions',
      icon: 'bx bxs-wallet',
      link: '/workspace/wallet',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'billing',
      label: 'Billing',
      icon: 'bx bxs-credit-card',
      link: '/workspace/billing',
      permission: 'EMPTY',
    },
    //Affiliate Settings
    {
      type: 'header',
      id: 'affilite_settings',
      label: 'Affiliate',
      permission: 'EMPTY',
    },
    // {
    //   type: 'page',
    //   id: 'affiliate-statistics',
    //   label: 'Statistics',
    //   icon: 'bx bx-stats',
    //   link: '/workspace/affiliate/settings',
    //   permission: 'EMPTY',
    // },
    {
      type: 'page',
      id: 'affiliate-visitor',
      label: 'Visitors & Conversion',
      icon: 'ri-eye-fill',
      link: '/workspace/affiliate/vnc',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'affiliate-payout',
      label: 'Commission & Payout',
      icon: 'ri-bank-fill',
      link: '/workspace/affiliate/cnp',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'affiliate-link',
      label: 'Links & Alias',
      icon: 'bx bx-link',
      link: '/workspace/affiliate/settings',
      permission: 'EMPTY',
    },
    //Affiliate Settings
    {
      type: 'header',
      id: 'header_help',
      label: 'Help & Support',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'support-ticket',
      label: 'Support Ticket',
      icon: 'las la-life-ring',
      link: '/workspace/ticket',
      permission: 'EMPTY',
    },
  ],
  WAPPFLOW: [
    {
      type: 'header',
      id: 'header_automation',
      label: 'Menu',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'dashboard_automation',
      label: 'All Products',
      icon: 'bx bxs-dashboard',
      link: '/products',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'flow',
      label: 'Flows',
      new: true,
      tag: 'Beta',
      tagClass: 'badge bg-info',
      icon: 'bx bx-fullscreen',
      link: '/products/flows',
      permission: 'CRM.CHANNEL',
    },
    // {
    //   type: 'header',
    //   id: 'header_template',
    //   label: 'Template',
    //   permission: 'CRM.CHANNEL',
    // },
    // {
    //   type: 'page',
    //   id: 'my-template',
    //   label: 'Templates',
    //   icon: 'bx bxs-book-content',
    //   link: '/products/flows/template',
    //   permission: 'CRM.CHANNEL',
    // },
  ],
  WAPPWIDGET: [
    {
      type: 'header',
      id: 'header_automation',
      label: 'Menu',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'dashboard_automation',
      label: 'All Products',
      icon: 'bx bxs-dashboard',
      link: '/products',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'widget',
      label: 'Widget',
      new: true,
      tag: 'Beta',
      tagClass: 'badge bg-info',
      icon: 'bx bx-conversation',
      link: '/products/widget',
      permission: 'CRM.CHANNEL',
    },
    // {
    //   type: 'header',
    //   id: 'header_template',
    //   label: 'Template',
    //   permission: 'CRM.CHANNEL',
    // },
    // {
    //   type: 'page',
    //   id: 'my-template',
    //   label: 'Templates',
    //   icon: 'bx bxs-book-content',
    //   link: '/products/flows/template',
    //   permission: 'CRM.CHANNEL',
    // },
  ],
  PAYMENTS: [
    {
      type: 'header',
      id: 'header_payment',
      label: 'Menu',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'dashboard_all_products',
      label: 'All Products',
      icon: 'bx bxs-dashboard',
      link: '/products',
      permission: 'EMPTY',
    },
    // {
    //   type: 'page',
    //   id: 'payment_analytics',
    //   label: 'Analytics',
    //   icon: 'bx bx-tachometer',
    //   link: '/products/payment',
    //   permission: 'CRM.CHANNEL',
    // },
    // {
    //   type: 'header',
    //   id: 'header_communication',
    //   label: 'Communication',
    //   permission: 'CRM.CHANNEL',
    // },
    // {
    //   type: 'page',
    //   id: 'payment_campaign',
    //   label: 'Campaign',
    //   icon: 'bx bxs-megaphone',
    //   link: '/products/payment/campaign',
    //   permission: 'CRM.CHANNEL',
    // },
    // {
    //   type: 'page',
    //   id: 'payment_message',
    //   label: 'Payment Messages',
    //   icon: 'bx bx-chat',
    //   link: '/products/payment/message',
    //   permission: 'CRM.CHANNEL',
    // },
    // {
    //   type: 'header',
    //   id: 'header_contact',
    //   label: 'Contacts',
    //   permission: 'CRM.CHANNEL',
    // },
    // {
    //   type: 'page',
    //   id: 'payment_customers',
    //   label: 'Customers',
    //   icon: 'bx bxs-user',
    //   link: '/products/payment/customer',
    //   permission: 'CRM.CHANNEL',
    // },
    {
      type: 'page',
      id: 'payment_orders',
      label: 'Payment Orders',
      icon: 'bx bx-file',
      link: '/products/payment/order',
      permission: 'NATIVE_PAYMENT.PURCHASE_ORDER',
    },
    // {
    //   type: 'header',
    //   id: 'header_content',
    //   label: 'Content',
    //   permission: 'CRM.CHANNEL',
    // },
    // {
    //   type: 'page',
    //   id: 'payment_vendor',
    //   label: 'Vendors',
    //   icon: 'bx bx-store',
    //   link: '/products/payment/vendor',
    //   permission: 'CRM.CHANNEL',
    // },
    // {
    //   type: 'page',
    //   id: 'product',
    //   label: 'Products',
    //   icon: 'bx bx-package',
    //   link: '/products/payment/product',
    //   permission: 'CRM.CHANNEL',
    // },
    {
      type: 'header',
      id: 'header_setting',
      label: 'Settings',
      permission: 'NATIVE_PAYMENT.PAYMENT_GATEWAY',
    },
    {
      type: 'page',
      id: 'payment_gateway',
      label: 'Payment Gateways',
      icon: 'bx bxs-bank',
      link: '/products/payment/gateway',
      permission: 'NATIVE_PAYMENT.PAYMENT_GATEWAY',
    },
    {
      type: 'page',
      id: 'payment_automation',
      label: 'Automations',
      icon: 'bx bx-cog',
      link: '/products/payment/automation',
      permission: 'NATIVE_PAYMENT.WEBHOOK',
    },
  ],
  DIG: [
    {
      type: 'header',
      id: 'header_dig',
      label: 'Menu',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'dashboard_all_products',
      label: 'All Products',
      icon: 'bx bxs-dashboard',
      link: '/products',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'image_experience',
      label: 'Image Experience',
      icon: 'bx bx-image',
      link: '/image',
      permission: 'DIG.IMAGE_EXPERIENCE',
    },
    {
      type: 'page',
      id: 'pdf_experience',
      label: 'PDF Experience',
      icon: 'bx bx-image',
      link: '/pdf',
      permission: 'DIG.PDF_EXPERIENCE',
    },
    {
      type: 'page',
      id: 'storage',
      label: 'Storage',
      icon: 'bx bx-image',
      link: '/storage',
      permission: 'DIG.PDF_EXPERIENCE',
    },
  ],
  DEPARTMENT: [
    {
      type: 'header',
      id: 'header_dig',
      label: 'Menu',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'dashboard_all_products',
      label: 'All Products',
      icon: 'bx bxs-dashboard',
      link: '/products',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'department',
      label: 'Dashboard',
      icon: 'ri-line-chart-line',
      link: '/products/department/analytics',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'department',
      label: 'Departments',
      icon: 'bx bx-buildings',
      link: '/products/department',
      permission: 'EMPTY',
    },
    {
      type: 'page',
      id: 'role',
      label: 'Roles',
      icon: 'bx bx-id-card',
      link: '/products/department/role',
      permission: 'EMPTY',
    },
  ],
};

export default DefaultMenu;
