// Actions
export const API_RESPONSE_SUCCESS = 'API_RESPONSE_SUCCESS';
export const API_RESPONSE_ERROR = 'API_RESPONSE_ERROR';

export const CREATE_IMAGE_EXP = 'CREATE_IMAGE_EXP';
export const LIST_IMAGE_EXP = 'LIST_IMAGE_EXP';
export const UPDATE_IMAGE_EXP = 'UPDATE_IMAGE_EXP';
export const FIND_IMAGE_EXP = 'FIND_IMAGE_EXP';
export const DELETE_IMAGE_EXP = 'DELETE_IMAGE_EXP';

export const RESET_IMAGE_EXP = 'RESET_IMAGE_EXP';
