// Actions
export const API_RESPONSE_SUCCESS = 'API_RESPONSE_SUCCESS';
export const API_RESPONSE_ERROR = 'API_RESPONSE_ERROR';

export const REGISTER_USER = 'REGISTER_USER';
export const GET_CURRENCIES = 'GET_CURRENCIES';

export const RESET_REGISTER_USER = 'RESET_REGISTER_USER';
