// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";

export const GET_USER_ROLES = "GET_USER_ROLES";
export const POST_USER_ROLES = "POST_USER_ROLES";

export const UPDATE_USER_ROLES = "UPDATE_USER_ROLES";
export const DELETE_USER_ROLES = "DELETE_USER_ROLES";

export const RESET_USER_ROLES = "RESET_USER_ROLES";
