// Actions
export const API_RESPONSE_SUCCESS = 'API_RESPONSE_SUCCESS';
export const API_RESPONSE_ERROR = 'API_RESPONSE_ERROR';

export const CREATE_PDF_EXP = 'CREATE_PDF_EXP';
export const LIST_PDF_EXP = 'LIST_PDF_EXP';
export const UPDATE_PDF_EXP = 'UPDATE_PDF_EXP';
export const FIND_PDF_EXP = 'FIND_PDF_EXP';
export const DELETE_PDF_EXP = 'DELETE_PDF_EXP';

export const RESET_PDF_EXP = 'RESET_PDF_EXP';


// Credit Actions
export const FETCH_PDF_CREDIT = 'FETCH_PDF_CREDIT';
export const FETCH_PDF_CREDIT_SUCCESS = 'FETCH_PDF_CREDIT_SUCCESS';
export const FETCH_PDF_CREDIT_FAIL = 'FETCH_PDF_CREDIT_FAIL';
export const RESET_PDF_CREDIT = 'RESET_PDF_CREDIT';