const waba_scope_list = [
  'waba.waba.READ',
  'waba.waba.CREATE',
  'waba.waba.UPDATE',
  'waba.waba.DELETE',
  'waba.report.READ',
  'waba.profile.READ',
  'waba.profile.UPDATE',
  'waba.conversation.READ',
  'waba.template.READ',
  'waba.template.CREATE',
  'waba.template.DELETE',
  'waba.template.UPDATE',
  'waba.webhook.READ',
  'waba.webhook.CREATE',
  'waba.webhook.DELETE',
  'waba.webhook.UPDATE',
  'waba.integration.READ',
];

const crm_scope_list = [
  'crm.live_chat.CREATE',
  'crm.channel.CREATE',
  'crm.contact.CREATE',
  'crm.custom_field.CREATE',
  'crm.canned_reply.CREATE',
  'crm.segment.CREATE',
  'crm.campaign.CREATE',
  'crm.trigger.CREATE',
  'crm.channel_group.CREATE',
  'crm.mass_broadcast.CREATE',
  'crm.live_chat.READ',
  'crm.channel.READ',
  'crm.contact.READ',
  'crm.custom_field.READ',
  'crm.canned_reply.READ',
  'crm.segment.READ',
  'crm.campaign.READ',
  'crm.trigger.READ',
  'crm.channel_group.READ',
  'crm.mass_broadcast.READ',
  'crm.live_chat.UPDATE',
  'crm.channel.UPDATE',
  'crm.contact.UPDATE',
  'crm.custom_field.UPDATE',
  'crm.canned_reply.UPDATE',
  'crm.segment.UPDATE',
  'crm.campaign.UPDATE',
  'crm.trigger.UPDATE',
  'crm.channel_group.UPDATE',
  'crm.mass_broadcast.UPDATE',
  'crm.live_chat.DELETE',
  'crm.channel.DELETE',
  'crm.contact.DELETE',
  'crm.custom_field.DELETE',
  'crm.canned_reply.DELETE',
  'crm.segment.DELETE',
  'crm.campaign.DELETE',
  'crm.trigger.DELETE',
  'crm.channel_group.DELETE',
  'crm.mass_broadcast.DELETE',
];

const automation_scope_list = [
  'automation.workflow.CREATE',
  'automation.data_store.CREATE',
  'automation.template.CREATE',
  'automation.template_store.CREATE',
  'automation.workflow.READ',
  'automation.data_store.READ',
  'automation.template.READ',
  'automation.template_store.READ',
  'automation.workflow.UPDATE',
  'automation.data_store.UPDATE',
  'automation.template.UPDATE',
  'automation.template_store.UPDATE',
  'automation.workflow.DELETE',
  'automation.data_store.DELETE',
  'automation.template.DELETE',
  'automation.template_store.DELETE',
];

const bot_scope_list = [
  'bot_builder.workflow.CREATE',
  'bot_builder.data_store.CREATE',
  'bot_builder.bot_field.CREATE',
  'bot_builder.template.CREATE',
  'bot_builder.template_store.CREATE',
  'bot_builder.workflow.READ',
  'bot_builder.data_store.READ',
  'bot_builder.bot_field.READ',
  'bot_builder.template.READ',
  'bot_builder.template_store.READ',
  'bot_builder.workflow.UPDATE',
  'bot_builder.data_store.UPDATE',
  'bot_builder.bot_field.UPDATE',
  'bot_builder.template.UPDATE',
  'bot_builder.template_store.UPDATE',
  'bot_builder.workflow.DELETE',
  'bot_builder.data_store.DELETE',
  'bot_builder.bot_field.DELETE',
  'bot_builder.template.DELETE',
  'bot_builder.template_store.DELETE',
];

const workspace_scope_list = [
  'workspace.billing.ALL',
  'workspace.ticket.READ',
  'workspace.ticket.UPDATE',
  'workspace.ticket.CREATE',
  'workspace.ticket.DELETE',
];

export { waba_scope_list, crm_scope_list, automation_scope_list, bot_scope_list, workspace_scope_list };
