export const LOGIN_USER = 'LOGIN_USER';
export const VERIFY_USER = 'VERIFY_USER';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';

export const GET_PANEL_USER = 'GET_PANEL_USER';
export const EXPORT_PANEL_USER = 'EXPORT_PANEL_USER';
export const LOGIN_AS = 'LOGIN_AS';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const API_ERROR = 'LOGIN_API_ERROR';

export const SOCIAL_LOGIN = 'SOCIAL_LOGIN';
export const USER_PROFILE = 'USER_PROFILE';

export const LOGIN_STATE_RESET = 'LOGIN_STATE_RESET';

export const API_RESPONSE_ERROR = 'API_RESPONSE_ERROR';
export const API_RESPONSE_SUCCESS = 'API_RESPONSE_SUCCESS';

export const GET_USER_CONSENT_STATUS = 'GET_USER_CONSENT_STATUS';
export const REGISTER_USER_CONSENT_STATUS = 'REGISTER_USER_CONSENT_STATUS';
